#!/bin/sh
set -eu

response="$(curl -fsS -X POST "${RADIUS_NTLM_AUTH_PROXY_URL}/auth" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"$1\",\"domain\":\"$2\",\"challenge\":\"$3\",\"nt_response\":\"$4\",\"request_nt_key\":true}")"

jq -re 'if .authenticated then "NT_KEY: " + .nt_key else halt_error(1) end' <<EOF
${response}
EOF
