proxy server {
    default_fallback = no
}

home_server primary {
    type = auth
    ipaddr = $ENV{RADIUS_PRIMARY_ADDRESS}
    port = $ENV{RADIUS_PRIMARY_PORT}
    secret = $ENV{RADIUS_PRIMARY_SECRET}
    response_window = $ENV{RADIUS_RESPONSE_WINDOW}
    response_timeouts = $ENV{RADIUS_RESPONSE_TIMEOUTS}
    zombie_period = $ENV{RADIUS_ZOMBIE_PERIOD}
    status_check = $ENV{RADIUS_PRIMARY_STATUS_CHECK}
    check_interval = $ENV{RADIUS_PRIMARY_CHECK_INTERVAL}
    check_timeout = $ENV{RADIUS_PRIMARY_CHECK_TIMEOUT}
    num_answers_to_alive = $ENV{RADIUS_PRIMARY_NUM_ANSWERS_TO_ALIVE}
}

home_server primary-accounting {
    type = acct
    ipaddr = $ENV{RADIUS_PRIMARY_ADDRESS}
    port = $ENV{RADIUS_PRIMARY_ACCOUNTING_PORT}
    secret = $ENV{RADIUS_PRIMARY_SECRET}
    response_window = $ENV{RADIUS_RESPONSE_WINDOW}
    response_timeouts = $ENV{RADIUS_RESPONSE_TIMEOUTS}
    zombie_period = $ENV{RADIUS_ZOMBIE_PERIOD}
    status_check = $ENV{RADIUS_PRIMARY_STATUS_CHECK}
    check_interval = $ENV{RADIUS_PRIMARY_CHECK_INTERVAL}
    check_timeout = $ENV{RADIUS_PRIMARY_CHECK_TIMEOUT}
    num_answers_to_alive = $ENV{RADIUS_PRIMARY_NUM_ANSWERS_TO_ALIVE}
}

home_server secondary {
    type = auth
    ipaddr = $ENV{RADIUS_SECONDARY_ADDRESS}
    port = $ENV{RADIUS_SECONDARY_PORT}
    secret = $ENV{RADIUS_SECONDARY_SECRET}
    response_window = $ENV{RADIUS_RESPONSE_WINDOW}
    response_timeouts = $ENV{RADIUS_RESPONSE_TIMEOUTS}
    zombie_period = $ENV{RADIUS_ZOMBIE_PERIOD}
    status_check = $ENV{RADIUS_SECONDARY_STATUS_CHECK}
    revive_interval = $ENV{RADIUS_SECONDARY_REVIVE_INTERVAL}
}

home_server default-access {
    virtual_server = default-access
}

home_server_pool failover {
    type = fail-over
    home_server = primary
    home_server = secondary
    fallback = default-access
}

home_server_pool primary-only {
    type = fail-over
    home_server = primary
}

home_server_pool accounting {
    type = fail-over
    home_server = primary-accounting
}

realm failover {
    auth_pool = failover
    nostrip
}

realm primary-only {
    auth_pool = primary-only
    nostrip
}

realm accounting {
    acct_pool = accounting
    nostrip
}
